#!/usr/bin/env bash
set -euo pipefail

repo_root="${1:-$(pwd)}"
repo_root="$(cd "$repo_root" && pwd)"

makefile=""
while IFS= read -r candidate; do
  if grep -Eq '^[[:space:]]*TWEAK_NAME[[:space:]]*[:+?]?=' "$candidate"; then
    makefile="$candidate"
    break
  fi
done < <(find "$repo_root" -maxdepth 6 -name Makefile -not -path '*/.git/*' -print)

if [ -z "$makefile" ]; then
  echo "No Theos tweak Makefile with TWEAK_NAME was found under $repo_root" >&2
  exit 1
fi

project_dir="$(dirname "$makefile")"
target_name="$(awk -F'=' '/^[[:space:]]*TWEAK_NAME[[:space:]]*[:+?]?=/ { value=$2; gsub(/^[[:space:]]+|[[:space:]]+$/, "", value); split(value, names, /[[:space:]]+/); print names[1]; exit }' "$makefile")"

if [ -z "$target_name" ]; then
  echo "Found Makefile at $makefile, but could not read the primary TWEAK_NAME." >&2
  exit 1
fi

if ! [[ "$target_name" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]]; then
  echo "Unsafe or unsupported TWEAK_NAME: $target_name" >&2
  exit 1
fi

required_sources=(
  "$repo_root/P6YCompat/P6YCompatCore.m"
  "$repo_root/P6YCompat/P6YDelayedInit.xm"
  "$repo_root/P6YCompat/P6YDelayedGroups.xm"
)

for source in "${required_sources[@]}"; do
  if [ ! -f "$source" ]; then
    echo "Required compatibility source is missing: $source" >&2
    exit 1
  fi
done

payload_filter="$project_dir/${target_name}.plist"
bootstrap_filter="$project_dir/P6YBootstrap.plist"

for filter in "$payload_filter" "$bootstrap_filter"; do
  if [ ! -f "$filter" ]; then
    echo "Required Theos filter plist is missing: $filter" >&2
    exit 1
  fi
  if command -v plutil >/dev/null 2>&1; then
    plutil -lint "$filter" >/dev/null
  fi
done

rel_compat_dir="$(python3 - "$repo_root" "$project_dir" <<'PY'
import os
import sys
print(os.path.relpath(os.path.join(sys.argv[1], "P6YCompat"), sys.argv[2]))
PY
)"

hookf_sources="$(grep -RIl --exclude-dir=.git --include='*.x' --include='*.xm' --include='*.xi' --include='*.xmi' '%hookf' "$project_dir" 2>/dev/null || true)"
forced_substrate_sources="$(grep -RIl --exclude-dir=.git --include='*.x' --include='*.xm' --include='*.xi' --include='*.xmi' -E '%config\([^)]*generator[[:space:]]*=[[:space:]]*(MobileSubstrate|libhooker)' "$project_dir" 2>/dev/null || true)"

payload_generator="internal"
if [ -n "$hookf_sources" ] || [ -n "$forced_substrate_sources" ]; then
  payload_generator="MobileSubstrate"
fi

payload_header="$repo_root/P6YCompat/P6YFeaturePayloadName.h"
payload_header_tmp="${payload_header}.tmp"
cat > "$payload_header_tmp" <<EOF
#import <Foundation/Foundation.h>

// Generated by scripts/wire_p6ycompat.sh for this build.
#ifndef P6Y_FEATURE_DYLIB_NAME
#define P6Y_FEATURE_DYLIB_NAME @"${target_name}.dylib"
#endif
EOF
mv "$payload_header_tmp" "$payload_header"

python3 - "$makefile" "$target_name" "$rel_compat_dir" "$payload_generator" <<'PY'
from pathlib import Path
import re
import sys

makefile = Path(sys.argv[1])
target = sys.argv[2]
compat = sys.argv[3]
payload_generator = sys.argv[4]
text = makefile.read_text(encoding="utf-8")

begin = "# BEGIN P6Y LOGIN-SAFE IPA BUILD"
end = "# END P6Y LOGIN-SAFE IPA BUILD"

text = re.sub(rf"\n?{re.escape(begin)}.*?{re.escape(end)}\n?", "\n", text, flags=re.S)
text = "\n".join(
    line for line in text.splitlines()
    if not ("P6YCompatCore.m" in line and "_FILES" in line)
) + "\n"

generator_line = ""
if payload_generator == "internal":
    generator_line = f"{target}_LOGOS_DEFAULT_GENERATOR = internal\n"

block = f"""
{begin}
# Keep the original target as a delayed feature payload. When possible, compile
# it with Logos' Objective-C runtime generator so the IPA is self-contained.
{generator_line}
# Only this small bootstrap dylib is injected into TikTok's executable. It loads
# {target}.dylib with dlopen after TikTok reaches verified normal UI.
TWEAK_NAME += P6YBootstrap
P6YBootstrap_FILES = {compat}/P6YCompatCore.m {compat}/P6YDelayedInit.xm {compat}/P6YDelayedGroups.xm
P6YBootstrap_FRAMEWORKS = Foundation UIKit
P6YBootstrap_CFLAGS = -fobjc-arc
P6YBootstrap_LOGOS_DEFAULT_GENERATOR = internal
{end}
"""

include_pattern = re.compile(r"^\s*include\s+.*(?:THEOS_MAKE_PATH|THEOS).*tweak\.mk\s*$", re.M)
match = include_pattern.search(text)
if not match:
    raise SystemExit(f"Could not find theos tweak.mk include in {makefile}")

text = text[:match.start()] + block + "\n" + text[match.start():]
makefile.write_text(text, encoding="utf-8")
PY

echo "Configured delayed feature payload and login-safe bootstrap in $makefile"
echo "project_dir=$project_dir"
echo "makefile=$makefile"
echo "target_name=$target_name"
echo "payload_dylib=${target_name}.dylib"
echo "bootstrap_dylib=P6YBootstrap.dylib"
echo "payload_generator=$payload_generator"
echo "payload_filter=$payload_filter"
echo "bootstrap_filter=$bootstrap_filter"
echo "payload_header=$payload_header"

if [ -n "$hookf_sources" ]; then
  echo "hookf_sources<<EOF"
  printf '%s\n' "$hookf_sources"
  echo "EOF"
fi
if [ -n "$forced_substrate_sources" ]; then
  echo "forced_substrate_sources<<EOF"
  printf '%s\n' "$forced_substrate_sources"
  echo "EOF"
fi
